# dbt/models/schema.yml

version: 2

models:
  - name: user_sessions
    description: "Aggregated metrics per user"
    columns:
      - name: user_id
        tests: [not_null]
      - name: total_visits
      - name: avg_duration

  - name: page_stats
    description: "Aggregated metrics per page"
    columns:
      - name: page
        tests: [not_null]
      - name: total_visits
      - name: avg_duration